#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

####################
# links to add

# templates to expand
    	templates2events( "/etc/wordpress/wp-config.php" , qw( conf-wordpress bootstrap-console-save post-upgrade) );
        templates2events( "/etc/e-smith/sql/init/80wordpress" , qw( conf-wordpress bootstrap-console-save post-upgrade) );
	templates2events( "/etc/httpd/conf/httpd.conf", "conf-wordpress" );

# services to launch on event
	safe_symlink("sigusr1", "root/etc/e-smith/events/conf-wordpress/services2adjust/httpd-e-smith");
        safe_symlink("restart", "root/etc/e-smith/events/conf-wordpress/services2adjust/mysql.init");

# actions to perform
	safe_symlink("../actions/wordpress", "root/etc/e-smith/events/conf-wordpress/20wordpress");
	safe_symlink("../actions/wordpress", "root/etc/e-smith/events/bootstrap-console-save/20wordpress");
        safe_symlink("../actions/wordpress", "root/etc/e-smith/events/console-save/20wordpress");

